mybatis:
  type-aliases-package: com.tuum.api.tuum.entity
  type-handlers-package: com.tuum.api.tuum.entityMapper
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
spring:
  rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    username: guest
  datasource:
    url: jdbc:postgresql://letsecure.az:5432/tuum_db #62.171.153.79
    driverClassName: org.postgresql.Driver    #    driverClassName: 'oracle.jdbc.OracleDriver'
    username: tuum_db
    password: '4`duGn:Rc^pK8A+<2cnn.#{='
tuum:
  rabbitmq:
    routingkey: tuum.routingkey
    queue: tuum.queue
    exchange: tuum.exchange
